version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
        - name: id
          description: "primary key of the table"
          tests:
            - unique
            - accepted_values:
                values: [1,2,3,4,5,6,7,8,9,10]
                quote: false
    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
        - name: id
          description: "primary key of the table"
          tests:
            - unique
            - not_null
            - relationships:
                to: ref('my_first_dbt_model')
                field: id
    - name: cumulative_orders_by_date
      description: "section 2 assignment to aggregate cumulative sales for the order date"
    - name: incremental_date
    - name: incremental_time

sources:
  - name: sample
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders
  - name: sample2
    database: snowflake_sample_data
    schema: tpch_sf001
    tables:
      - name: customer

